- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Download and Install Oh-My-Zsh for users
  ansible.builtin.shell:
    cmd: |
      wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O /home/{{ item.name }}/install.sh
      sh /home/{{ item.name }}/install.sh --unattended
  args:
    chdir: "/home/{{ item.name }}"
  become_user: "{{ item.name }}"
  loop: "{{ users }}"
  when: item.shell == "/bin/zsh"