- name: Configure SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  loop:
    - "PermitRootLogin no"
    - "PasswordAuthentication no"
    - "LogLevel VERBOSE"
    - "X11Forwarding no"
  notify: Reload SSH