- name: Configure SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
    state: present
  loop:
    - "PermitRootLogin no"
    - "PasswordAuthentication no"
    - "LogLevel VERBOSE"
    - "X11Forwarding no"

# - name: Restart SSH service
#   ansible.builtin.service:
#     name: ssh
#     state: restarted