version: '3.8'

services:
  ansible_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "22:22"
      - "80:80"
    volumes:
      - ./ansible:/ansible
    container_name: ansible_test