- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start Nginx if not running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  when: ansible_facts.services['nginx'] is not defined or ansible_facts.services['nginx'].state != 'running'

- name: Configure Nginx
  ansible.builtin.template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload Nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Reload Nginx