all:
  hosts:
    test_server:
      ansible_host: 127.0.0.1
      ansible_port: 22
      ansible_user: root
      #ansible_ssh_pass: password
      ansible_python_interpreter: /usr/bin/python3
      ansible_connection: ssh 
      ansible_ssh_private_key_file: ~/.ssh/id_rsa